import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/app/_apolloConfig/apolloClientWrapper";
import { NextAuthProvider } from "@/app/_nextAuthProvider/NextAuthProvider";
import Sidebar from "./_components/layout/sidebar";
import Navbar from "./_components/layout/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <NextAuthProvider>
          <body>
            {" "}
            <div className="relative flex min-h-screen bg-gray-100">
              {/* Sidebar */}
              <Sidebar /> {/* Sidebar bileşenini çağırıyoruz */}
              {/* Main content */}
              <div className="flex-1">
                <Navbar />
                <div className="flex-1 p-6 pt-16 md:pt-6">
                  {children} {/* Dinamik sayfa içeriği */}
                </div>
              </div>
            </div>
          </body>
        </NextAuthProvider>
      </ApolloWrapper>
    </html>
  );
}
